"""
Comprehensive club data with players, managers, trophies, and historical facts
for generating 3250+ questions across all 96 clubs
"""

COMPREHENSIVE_CLUB_DATA = {
    # ==================== PREMIER LEAGUE ====================
    "Arsenal": {
        "nickname": "The Gunners",
        "colors": "Red and White",
        "stadium": "Emirates Stadium",
        "previous_stadiums": ["Highbury", "Manor Ground"],
        "city": "London",
        "founded": 1886,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["Thierry Henry", "Dennis Bergkamp", "Patrick Vieira", "Tony Adams", "Robert Pires", "Ian Wright", "David Seaman", "Liam Brady"],
        "current_players": ["Bukayo Saka", "Martin Odegaard", "William Saliba", "Declan Rice", "Gabriel Jesus"],
        "historical_players": ["Cliff Bastin", "Ted Drake", "Charlie George", "Frank McLintock", "Kenny Sansom"],
        "managers": ["Arsene Wenger", "Mikel Arteta", "George Graham", "Herbert Chapman", "Bertie Mee", "Unai Emery"],
        "trophies": {"league_titles": 13, "fa_cups": 14, "league_cups": 2, "european_trophies": 0},
        "rivals": ["Tottenham Hotspur", "Chelsea", "Manchester United"],
        "derby_name": "North London Derby",
        "record_signing": "Declan Rice",
        "record_fee": "105 million",
        "top_scorer": "Thierry Henry",
        "top_scorer_goals": 228,
        "most_appearances": "David O'Leary",
        "most_appearances_count": 722,
        "notable_seasons": ["2003-04 Invincibles", "1970-71 Double", "1997-98 Double"],
        "famous_matches": ["Arsenal 4-4 Tottenham 2008", "Arsenal 7-3 Newcastle 2012"],
        "shirt_sponsor": "Emirates",
        "kit_manufacturer": "Adidas",
        "owner": "Stan Kroenke",
        "captain": "Martin Odegaard",
        "mascot": "Gunnersaurus"
    },
    "Aston Villa": {
        "nickname": "The Villans",
        "colors": "Claret and Blue",
        "stadium": "Villa Park",
        "previous_stadiums": ["Wellington Road", "Perry Barr"],
        "city": "Birmingham",
        "founded": 1874,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["Paul McGrath", "Peter Withe", "Brian Little", "Gary Shaw", "Dennis Mortimer", "Gordon Cowans"],
        "current_players": ["Ollie Watkins", "Emiliano Martinez", "John McGinn", "Leon Bailey", "Ezri Konsa"],
        "historical_players": ["Billy Walker", "Pongo Waring", "Charlie Aitken", "Johnny Dixon"],
        "managers": ["Brian Little", "Ron Atkinson", "Graham Taylor", "Unai Emery", "Martin O'Neill", "Ron Saunders"],
        "trophies": {"league_titles": 7, "fa_cups": 7, "league_cups": 5, "european_trophies": 1},
        "rivals": ["Birmingham City", "West Bromwich Albion", "Wolverhampton Wanderers"],
        "derby_name": "Second City Derby",
        "record_signing": "Moussa Diaby",
        "record_fee": "52 million",
        "top_scorer": "Billy Walker",
        "top_scorer_goals": 244,
        "most_appearances": "Charlie Aitken",
        "most_appearances_count": 660,
        "notable_seasons": ["1980-81 League Champions", "1981-82 European Cup Winners"],
        "famous_matches": ["Aston Villa 1-0 Bayern Munich 1982 European Cup Final"],
        "shirt_sponsor": "Betano",
        "kit_manufacturer": "Adidas",
        "owner": "Nassef Sawiris and Wes Edens",
        "captain": "John McGinn",
        "mascot": "Hercules the Lion"
    },
    "AFC Bournemouth": {
        "nickname": "The Cherries",
        "colors": "Red and Black",
        "stadium": "Vitality Stadium",
        "previous_stadiums": ["Dean Court"],
        "city": "Bournemouth",
        "founded": 1899,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["Ted MacDougall", "Steve Fletcher", "Harry Redknapp", "Luther Blissett"],
        "current_players": ["Dominic Solanke", "Marcus Tavernier", "Lloyd Kelly", "Philip Billing"],
        "historical_players": ["Ron Eyre", "Dickie Dowsett", "John Bond"],
        "managers": ["Eddie Howe", "Harry Redknapp", "Tony Pulis", "Sean O'Driscoll", "Andoni Iraola"],
        "trophies": {"league_titles": 0, "fa_cups": 0, "league_cups": 0, "european_trophies": 0},
        "rivals": ["Southampton", "Portsmouth"],
        "derby_name": "South Coast Derby",
        "record_signing": "Jefferson Lerma",
        "record_fee": "25 million",
        "top_scorer": "Ron Eyre",
        "top_scorer_goals": 202,
        "most_appearances": "Steve Fletcher",
        "most_appearances_count": 628,
        "notable_seasons": ["2014-15 Championship Winners"],
        "famous_matches": ["Bournemouth 4-3 Liverpool 2016"],
        "shirt_sponsor": "Dafabet",
        "kit_manufacturer": "Umbro",
        "owner": "Bill Foley",
        "captain": "Lewis Cook",
        "mascot": "Cherry Bear"
    },
    "Brentford": {
        "nickname": "The Bees",
        "colors": "Red and White",
        "stadium": "Gtech Community Stadium",
        "previous_stadiums": ["Griffin Park"],
        "city": "London",
        "founded": 1889,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["Jim Towers", "Dean Holdsworth", "Peter Gelson", "Marcus Forss"],
        "current_players": ["Ivan Toney", "Bryan Mbeumo", "David Raya", "Christian Norgaard"],
        "historical_players": ["Jack Holliday", "Billy Scott", "Idris Hopkins"],
        "managers": ["Thomas Frank", "Dean Smith", "Mark Warburton", "Uwe Rosler"],
        "trophies": {"league_titles": 0, "fa_cups": 0, "league_cups": 0, "european_trophies": 0},
        "rivals": ["Fulham", "Queens Park Rangers"],
        "derby_name": "West London Derby",
        "record_signing": "Keane Lewis-Potter",
        "record_fee": "20 million",
        "top_scorer": "Jim Towers",
        "top_scorer_goals": 163,
        "most_appearances": "Ken Coote",
        "most_appearances_count": 559,
        "notable_seasons": ["2020-21 Championship Play-off Winners"],
        "famous_matches": ["Brentford 2-0 Arsenal 2021"],
        "shirt_sponsor": "Hollywoodbets",
        "kit_manufacturer": "Umbro",
        "owner": "Matthew Benham",
        "captain": "Pontus Jansson",
        "mascot": "Buzz Bee"
    },
    "Brighton & Hove Albion": {
        "nickname": "The Seagulls",
        "colors": "Blue and White",
        "stadium": "Amex Stadium",
        "previous_stadiums": ["Goldstone Ground", "Withdean Stadium"],
        "city": "Brighton",
        "founded": 1901,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["Peter Ward", "Mark Lawrenson", "Gordon Smith", "Bobby Zamora"],
        "current_players": ["Kaoru Mitoma", "Evan Ferguson", "Moises Caicedo", "Pascal Gross"],
        "historical_players": ["Kit Napier", "Dennis Gordon", "Jimmy Langley"],
        "managers": ["Graham Potter", "Chris Hughton", "Roberto De Zerbi", "Gus Poyet", "Fabian Hurzeler"],
        "trophies": {"league_titles": 0, "fa_cups": 0, "league_cups": 0, "european_trophies": 0},
        "rivals": ["Crystal Palace"],
        "derby_name": "M23 Derby",
        "record_signing": "Georginio Rutter",
        "record_fee": "40 million",
        "top_scorer": "Tommy Cook",
        "top_scorer_goals": 123,
        "most_appearances": "Kerry Mayo",
        "most_appearances_count": 466,
        "notable_seasons": ["2022-23 Premier League 6th Place"],
        "famous_matches": ["Brighton 4-1 Chelsea 2022"],
        "shirt_sponsor": "American Express",
        "kit_manufacturer": "Nike",
        "owner": "Tony Bloom",
        "captain": "Lewis Dunk",
        "mascot": "Gully the Seagull"
    },
    "Chelsea": {
        "nickname": "The Blues",
        "colors": "Blue",
        "stadium": "Stamford Bridge",
        "previous_stadiums": [],
        "city": "London",
        "founded": 1905,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["Frank Lampard", "John Terry", "Didier Drogba", "Gianfranco Zola", "Eden Hazard", "Peter Osgood", "Ron Harris", "Petr Cech"],
        "current_players": ["Cole Palmer", "Enzo Fernandez", "Reece James", "Mykhailo Mudryk", "Nicolas Jackson"],
        "historical_players": ["Roy Bentley", "Bobby Tambling", "Kerry Dixon", "Pat Nevin"],
        "managers": ["Jose Mourinho", "Carlo Ancelotti", "Thomas Tuchel", "Antonio Conte", "Mauricio Pochettino", "Claudio Ranieri"],
        "trophies": {"league_titles": 6, "fa_cups": 8, "league_cups": 5, "european_trophies": 2},
        "rivals": ["Arsenal", "Tottenham Hotspur", "Fulham"],
        "derby_name": "West London Derby",
        "record_signing": "Enzo Fernandez",
        "record_fee": "107 million",
        "top_scorer": "Frank Lampard",
        "top_scorer_goals": 211,
        "most_appearances": "Ron Harris",
        "most_appearances_count": 795,
        "notable_seasons": ["2004-05 Premier League Winners", "2011-12 Champions League Winners", "2020-21 Champions League Winners"],
        "famous_matches": ["Chelsea 2-1 Barcelona 2012", "Chelsea 1-0 Manchester City 2021 CL Final"],
        "shirt_sponsor": "Infinite Athlete",
        "kit_manufacturer": "Nike",
        "owner": "Todd Boehly",
        "captain": "Reece James",
        "mascot": "Stamford the Lion"
    },
    "Crystal Palace": {
        "nickname": "The Eagles",
        "colors": "Red and Blue",
        "stadium": "Selhurst Park",
        "previous_stadiums": ["The Nest"],
        "city": "London",
        "founded": 1905,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["Wilfried Zaha", "Ian Wright", "Mark Bright", "Jim Cannon", "Geoff Thomas"],
        "current_players": ["Eberechi Eze", "Michael Olise", "Marc Guehi", "Jean-Philippe Mateta"],
        "historical_players": ["Peter Simpson", "Johnny Byrne", "Steve Kember"],
        "managers": ["Roy Hodgson", "Patrick Vieira", "Alan Pardew", "Sam Allardyce", "Oliver Glasner"],
        "trophies": {"league_titles": 0, "fa_cups": 0, "league_cups": 0, "european_trophies": 0},
        "rivals": ["Brighton & Hove Albion", "Millwall", "Charlton Athletic"],
        "derby_name": "M23 Derby",
        "record_signing": "Chris Richards",
        "record_fee": "18 million",
        "top_scorer": "Peter Simpson",
        "top_scorer_goals": 165,
        "most_appearances": "Jim Cannon",
        "most_appearances_count": 660,
        "notable_seasons": ["1990-91 FA Cup Final", "2015-16 FA Cup Final"],
        "famous_matches": ["Crystal Palace 3-3 Liverpool 2014"],
        "shirt_sponsor": "Cinch",
        "kit_manufacturer": "Macron",
        "owner": "Steve Parish",
        "captain": "Marc Guehi",
        "mascot": "Pete the Eagle"
    },
    "Everton": {
        "nickname": "The Toffees",
        "colors": "Blue and White",
        "stadium": "Goodison Park",
        "previous_stadiums": ["Anfield"],
        "city": "Liverpool",
        "founded": 1878,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["Dixie Dean", "Alan Ball", "Neville Southall", "Kevin Ratcliffe", "Peter Reid", "Dave Watson", "Tim Cahill"],
        "current_players": ["Dominic Calvert-Lewin", "Jordan Pickford", "Dwight McNeil", "James Tarkowski"],
        "historical_players": ["Ted Sagar", "Tommy Lawton", "Brian Labone", "Howard Kendall"],
        "managers": ["Howard Kendall", "David Moyes", "Carlo Ancelotti", "Sean Dyche", "Roberto Martinez"],
        "trophies": {"league_titles": 9, "fa_cups": 5, "league_cups": 0, "european_trophies": 1},
        "rivals": ["Liverpool"],
        "derby_name": "Merseyside Derby",
        "record_signing": "Amadou Onana",
        "record_fee": "35 million",
        "top_scorer": "Dixie Dean",
        "top_scorer_goals": 383,
        "most_appearances": "Neville Southall",
        "most_appearances_count": 751,
        "notable_seasons": ["1984-85 League Champions", "1986-87 League Champions"],
        "famous_matches": ["Everton 4-4 Liverpool 1991"],
        "shirt_sponsor": "Stake",
        "kit_manufacturer": "Hummel",
        "owner": "Farhad Moshiri",
        "captain": "Seamus Coleman",
        "mascot": "Changy the Elephant"
    },
    "Fulham": {
        "nickname": "The Cottagers",
        "colors": "White and Black",
        "stadium": "Craven Cottage",
        "previous_stadiums": [],
        "city": "London",
        "founded": 1879,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["Johnny Haynes", "George Cohen", "Bobby Robson", "Louis Saha", "Clint Dempsey"],
        "current_players": ["Aleksandar Mitrovic", "Joao Palhinha", "Andreas Pereira", "Antonee Robinson"],
        "historical_players": ["Eddie Lowe", "Bedford Jezzard", "Jim Langley"],
        "managers": ["Roy Hodgson", "Marco Silva", "Felix Magath", "Claudio Ranieri", "Scott Parker"],
        "trophies": {"league_titles": 0, "fa_cups": 0, "league_cups": 0, "european_trophies": 0},
        "rivals": ["Chelsea", "Queens Park Rangers", "Brentford"],
        "derby_name": "West London Derby",
        "record_signing": "Jean Michael Seri",
        "record_fee": "25 million",
        "top_scorer": "Gordon Davies",
        "top_scorer_goals": 178,
        "most_appearances": "Johnny Haynes",
        "most_appearances_count": 658,
        "notable_seasons": ["2009-10 Europa League Final"],
        "famous_matches": ["Fulham 4-1 Juventus 2010 Europa League"],
        "shirt_sponsor": "W88",
        "kit_manufacturer": "Adidas",
        "owner": "Shahid Khan",
        "captain": "Tom Cairney",
        "mascot": "Billy the Badger"
    },
    "Ipswich Town": {
        "nickname": "The Tractor Boys",
        "colors": "Blue and White",
        "stadium": "Portman Road",
        "previous_stadiums": ["Broom Hill", "Brook's Hall"],
        "city": "Ipswich",
        "founded": 1878,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["John Wark", "Mick Mills", "Terry Butcher", "Kevin Beattie", "Frans Thijssen"],
        "current_players": ["Nathan Broadhead", "Leif Davis", "Wes Burns", "Sam Morsy"],
        "historical_players": ["Ray Crawford", "Ted Phillips", "Arnold Muhren"],
        "managers": ["Bobby Robson", "Alf Ramsey", "George Burley", "Kieran McKenna", "Roy Keane"],
        "trophies": {"league_titles": 1, "fa_cups": 1, "league_cups": 0, "european_trophies": 1},
        "rivals": ["Norwich City"],
        "derby_name": "East Anglian Derby",
        "record_signing": "Matteo Pessina",
        "record_fee": "8 million",
        "top_scorer": "Ray Crawford",
        "top_scorer_goals": 227,
        "most_appearances": "Mick Mills",
        "most_appearances_count": 741,
        "notable_seasons": ["1961-62 League Champions", "1980-81 UEFA Cup Winners"],
        "famous_matches": ["Ipswich Town 5-2 AZ Alkmaar 1981 UEFA Cup Final"],
        "shirt_sponsor": "Ed Sheeran",
        "kit_manufacturer": "Umbro",
        "owner": "Gamechanger 20 Ltd",
        "captain": "Sam Morsy",
        "mascot": "Bluey the Horse"
    },
    "Leicester City": {
        "nickname": "The Foxes",
        "colors": "Blue",
        "stadium": "King Power Stadium",
        "previous_stadiums": ["Filbert Street"],
        "city": "Leicester",
        "founded": 1884,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["Gary Lineker", "Peter Shilton", "Gordon Banks", "Jamie Vardy", "N'Golo Kante", "Riyad Mahrez"],
        "current_players": ["Jamie Vardy", "Wilfred Ndidi", "James Maddison", "Kiernan Dewsbury-Hall"],
        "historical_players": ["Arthur Chandler", "Sep Smith", "Keith Weller", "Frank Worthington"],
        "managers": ["Claudio Ranieri", "Brendan Rodgers", "Martin O'Neill", "Nigel Pearson", "Steve Cooper"],
        "trophies": {"league_titles": 1, "fa_cups": 1, "league_cups": 3, "european_trophies": 0},
        "rivals": ["Nottingham Forest", "Derby County", "Coventry City"],
        "derby_name": "East Midlands Derby",
        "record_signing": "Wesley Fofana",
        "record_fee": "36 million",
        "top_scorer": "Arthur Chandler",
        "top_scorer_goals": 273,
        "most_appearances": "Graham Cross",
        "most_appearances_count": 599,
        "notable_seasons": ["2015-16 Premier League Champions"],
        "famous_matches": ["Leicester City 3-1 Everton 2016 Title Winning Season"],
        "shirt_sponsor": "BC Game",
        "kit_manufacturer": "Adidas",
        "owner": "Aiyawatt Srivaddhanaprabha",
        "captain": "Jamie Vardy",
        "mascot": "Filbert Fox"
    },
    "Liverpool": {
        "nickname": "The Reds",
        "colors": "Red",
        "stadium": "Anfield",
        "previous_stadiums": [],
        "city": "Liverpool",
        "founded": 1892,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["Steven Gerrard", "Kenny Dalglish", "Ian Rush", "Robbie Fowler", "John Barnes", "Kevin Keegan", "Graeme Souness", "Mohamed Salah"],
        "current_players": ["Mohamed Salah", "Virgil van Dijk", "Trent Alexander-Arnold", "Darwin Nunez", "Alisson"],
        "historical_players": ["Billy Liddell", "Roger Hunt", "Ray Clemence", "Tommy Smith", "Emlyn Hughes"],
        "managers": ["Bill Shankly", "Bob Paisley", "Jurgen Klopp", "Rafael Benitez", "Joe Fagan", "Kenny Dalglish", "Arne Slot"],
        "trophies": {"league_titles": 19, "fa_cups": 8, "league_cups": 10, "european_trophies": 6},
        "rivals": ["Manchester United", "Everton", "Manchester City"],
        "derby_name": "North West Derby",
        "record_signing": "Darwin Nunez",
        "record_fee": "85 million",
        "top_scorer": "Ian Rush",
        "top_scorer_goals": 346,
        "most_appearances": "Ian Callaghan",
        "most_appearances_count": 857,
        "notable_seasons": ["2018-19 Champions League Winners", "2019-20 Premier League Champions", "2004-05 Istanbul Miracle"],
        "famous_matches": ["Liverpool 3-3 AC Milan 2005 CL Final", "Barcelona 3-0 Liverpool then Liverpool 4-0 Barcelona 2019"],
        "shirt_sponsor": "Standard Chartered",
        "kit_manufacturer": "Nike",
        "owner": "Fenway Sports Group",
        "captain": "Virgil van Dijk",
        "mascot": "Mighty Red"
    },
    "Manchester City": {
        "nickname": "The Citizens",
        "colors": "Sky Blue",
        "stadium": "Etihad Stadium",
        "previous_stadiums": ["Maine Road", "Hyde Road"],
        "city": "Manchester",
        "founded": 1880,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["Sergio Aguero", "David Silva", "Vincent Kompany", "Yaya Toure", "Colin Bell", "Francis Lee", "Mike Summerbee"],
        "current_players": ["Erling Haaland", "Kevin De Bruyne", "Phil Foden", "Rodri", "Bernardo Silva"],
        "historical_players": ["Tommy Johnson", "Eric Brook", "Bert Trautmann", "Billy Meredith"],
        "managers": ["Pep Guardiola", "Roberto Mancini", "Manuel Pellegrini", "Joe Mercer", "Brian Horton"],
        "trophies": {"league_titles": 9, "fa_cups": 7, "league_cups": 8, "european_trophies": 1},
        "rivals": ["Manchester United", "Liverpool", "Chelsea"],
        "derby_name": "Manchester Derby",
        "record_signing": "Jack Grealish",
        "record_fee": "100 million",
        "top_scorer": "Sergio Aguero",
        "top_scorer_goals": 260,
        "most_appearances": "Alan Oakes",
        "most_appearances_count": 680,
        "notable_seasons": ["2011-12 Aguero Moment", "2022-23 Treble Winners", "2017-18 Centurions"],
        "famous_matches": ["Manchester City 3-2 QPR 2012", "Manchester City 1-0 Inter Milan 2023 CL Final"],
        "shirt_sponsor": "Etihad Airways",
        "kit_manufacturer": "Puma",
        "owner": "Sheikh Mansour",
        "captain": "Kyle Walker",
        "mascot": "Moonchester and Moonbeam"
    },
    "Manchester United": {
        "nickname": "The Red Devils",
        "colors": "Red and White",
        "stadium": "Old Trafford",
        "previous_stadiums": ["Bank Street", "North Road"],
        "city": "Manchester",
        "founded": 1878,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["George Best", "Bobby Charlton", "Eric Cantona", "Ryan Giggs", "Wayne Rooney", "Paul Scholes", "Roy Keane", "Cristiano Ronaldo"],
        "current_players": ["Bruno Fernandes", "Marcus Rashford", "Casemiro", "Lisandro Martinez", "Rasmus Hojlund"],
        "historical_players": ["Denis Law", "Duncan Edwards", "Nobby Stiles", "Billy Meredith", "Jack Rowley"],
        "managers": ["Sir Alex Ferguson", "Matt Busby", "Jose Mourinho", "Louis van Gaal", "Erik ten Hag", "David Moyes"],
        "trophies": {"league_titles": 20, "fa_cups": 12, "league_cups": 6, "european_trophies": 3},
        "rivals": ["Liverpool", "Manchester City", "Leeds United", "Arsenal"],
        "derby_name": "Manchester Derby",
        "record_signing": "Paul Pogba",
        "record_fee": "89 million",
        "top_scorer": "Wayne Rooney",
        "top_scorer_goals": 253,
        "most_appearances": "Ryan Giggs",
        "most_appearances_count": 963,
        "notable_seasons": ["1998-99 Treble Winners", "2007-08 Champions League Winners", "1967-68 First English European Cup Winners"],
        "famous_matches": ["Manchester United 2-1 Bayern Munich 1999 CL Final", "Manchester United 7-1 Roma 2007"],
        "shirt_sponsor": "Snapdragon",
        "kit_manufacturer": "Adidas",
        "owner": "INEOS",
        "captain": "Bruno Fernandes",
        "mascot": "Fred the Red"
    },
    "Newcastle United": {
        "nickname": "The Magpies",
        "colors": "Black and White",
        "stadium": "St James' Park",
        "previous_stadiums": ["Chillingham Road", "St James' Park original"],
        "city": "Newcastle",
        "founded": 1892,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["Alan Shearer", "Jackie Milburn", "Kevin Keegan", "Peter Beardsley", "Malcolm Macdonald", "Les Ferdinand"],
        "current_players": ["Alexander Isak", "Bruno Guimaraes", "Sandro Tonali", "Kieran Trippier", "Anthony Gordon"],
        "historical_players": ["Hughie Gallacher", "Len White", "Bobby Mitchell", "Frank Hudspeth"],
        "managers": ["Kevin Keegan", "Sir Bobby Robson", "Rafa Benitez", "Eddie Howe", "Ruud Gullit"],
        "trophies": {"league_titles": 4, "fa_cups": 6, "league_cups": 0, "european_trophies": 1},
        "rivals": ["Sunderland", "Middlesbrough"],
        "derby_name": "Tyne-Wear Derby",
        "record_signing": "Alexander Isak",
        "record_fee": "63 million",
        "top_scorer": "Alan Shearer",
        "top_scorer_goals": 206,
        "most_appearances": "Jimmy Lawrence",
        "most_appearances_count": 496,
        "notable_seasons": ["1995-96 Almost Winners", "2022-23 Champions League Qualification"],
        "famous_matches": ["Newcastle 5-0 Manchester United 1996", "Liverpool 4-3 Newcastle 1996"],
        "shirt_sponsor": "Sela",
        "kit_manufacturer": "Adidas",
        "owner": "Saudi Public Investment Fund",
        "captain": "Jamaal Lascelles",
        "mascot": "Monty Magpie"
    },
    "Nottingham Forest": {
        "nickname": "The Reds",
        "colors": "Red and White",
        "stadium": "City Ground",
        "previous_stadiums": ["Town Ground", "Gregory Ground"],
        "city": "Nottingham",
        "founded": 1865,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["Peter Shilton", "John Robertson", "Stuart Pearce", "Roy Keane", "Des Walker", "Viv Anderson"],
        "current_players": ["Morgan Gibbs-White", "Taiwo Awoniyi", "Brennan Johnson", "Neco Williams"],
        "historical_players": ["Tinsley Lindley", "Bob McKinlay", "Henry Newton"],
        "managers": ["Brian Clough", "Frank Clark", "Steve Cooper", "Nuno Espirito Santo", "Billy Davies"],
        "trophies": {"league_titles": 1, "fa_cups": 2, "league_cups": 4, "european_trophies": 2},
        "rivals": ["Derby County", "Leicester City"],
        "derby_name": "East Midlands Derby",
        "record_signing": "Morgan Gibbs-White",
        "record_fee": "42 million",
        "top_scorer": "Grenville Morris",
        "top_scorer_goals": 217,
        "most_appearances": "Bob McKinlay",
        "most_appearances_count": 685,
        "notable_seasons": ["1977-78 League Champions", "1978-79 European Cup Winners", "1979-80 European Cup Winners"],
        "famous_matches": ["Nottingham Forest 1-0 Malmo 1979 European Cup Final"],
        "shirt_sponsor": "UNHCR",
        "kit_manufacturer": "Adidas",
        "owner": "Evangelos Marinakis",
        "captain": "Joe Worrall",
        "mascot": "Robin Hood"
    },
    "Southampton": {
        "nickname": "The Saints",
        "colors": "Red and White",
        "stadium": "St Mary's Stadium",
        "previous_stadiums": ["The Dell"],
        "city": "Southampton",
        "founded": 1885,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["Matt Le Tissier", "Alan Shearer", "Mick Channon", "Terry Paine", "Kevin Keegan"],
        "current_players": ["James Ward-Prowse", "Che Adams", "Mohammed Salisu", "Romeo Lavia"],
        "historical_players": ["Ron Davies", "Mike Channon", "Ted Bates"],
        "managers": ["Lawrie McMenemy", "Gordon Strachan", "Ronald Koeman", "Mauricio Pochettino", "Ralph Hasenhuttl"],
        "trophies": {"league_titles": 0, "fa_cups": 1, "league_cups": 0, "european_trophies": 0},
        "rivals": ["Portsmouth", "AFC Bournemouth"],
        "derby_name": "South Coast Derby",
        "record_signing": "Danny Ings",
        "record_fee": "20 million",
        "top_scorer": "Mick Channon",
        "top_scorer_goals": 228,
        "most_appearances": "Terry Paine",
        "most_appearances_count": 824,
        "notable_seasons": ["1975-76 FA Cup Winners"],
        "famous_matches": ["Southampton 1-0 Manchester United 1976 FA Cup Final"],
        "shirt_sponsor": "Sportsbet.io",
        "kit_manufacturer": "Hummel",
        "owner": "Sport Republic",
        "captain": "James Ward-Prowse",
        "mascot": "Sammy Saint"
    },
    "Tottenham Hotspur": {
        "nickname": "Spurs",
        "colors": "White and Navy",
        "stadium": "Tottenham Hotspur Stadium",
        "previous_stadiums": ["White Hart Lane"],
        "city": "London",
        "founded": 1882,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["Jimmy Greaves", "Glenn Hoddle", "Dave Mackay", "Danny Blanchflower", "Harry Kane", "Gareth Bale", "Son Heung-min"],
        "current_players": ["Son Heung-min", "James Maddison", "Richarlison", "Cristian Romero", "Micky van de Ven"],
        "historical_players": ["Bill Nicholson", "Steve Perryman", "Pat Jennings", "Ossie Ardiles"],
        "managers": ["Bill Nicholson", "Mauricio Pochettino", "Jose Mourinho", "Antonio Conte", "Ange Postecoglou"],
        "trophies": {"league_titles": 2, "fa_cups": 8, "league_cups": 4, "european_trophies": 2},
        "rivals": ["Arsenal", "Chelsea", "West Ham United"],
        "derby_name": "North London Derby",
        "record_signing": "Tanguy Ndombele",
        "record_fee": "63 million",
        "top_scorer": "Harry Kane",
        "top_scorer_goals": 280,
        "most_appearances": "Steve Perryman",
        "most_appearances_count": 866,
        "notable_seasons": ["1960-61 Double Winners", "2018-19 Champions League Final"],
        "famous_matches": ["Tottenham 3-2 Ajax 2019 CL Semi-Final"],
        "shirt_sponsor": "AIA",
        "kit_manufacturer": "Nike",
        "owner": "ENIC Group",
        "captain": "Son Heung-min",
        "mascot": "Chirpy the Cockerel"
    },
    "West Ham United": {
        "nickname": "The Hammers",
        "colors": "Claret and Blue",
        "stadium": "London Stadium",
        "previous_stadiums": ["Boleyn Ground", "Upton Park"],
        "city": "London",
        "founded": 1895,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["Bobby Moore", "Geoff Hurst", "Martin Peters", "Trevor Brooking", "Billy Bonds", "Paolo Di Canio"],
        "current_players": ["Declan Rice", "Jarrod Bowen", "Tomas Soucek", "Kurt Zouma", "Lucas Paqueta"],
        "historical_players": ["Vic Watson", "Johnny Byrne", "Alan Devonshire"],
        "managers": ["Ron Greenwood", "John Lyall", "David Moyes", "Sam Allardyce", "Slaven Bilic"],
        "trophies": {"league_titles": 0, "fa_cups": 3, "league_cups": 0, "european_trophies": 1},
        "rivals": ["Millwall", "Tottenham Hotspur", "Chelsea"],
        "derby_name": "Dockers Derby",
        "record_signing": "Lucas Paqueta",
        "record_fee": "51 million",
        "top_scorer": "Vic Watson",
        "top_scorer_goals": 326,
        "most_appearances": "Billy Bonds",
        "most_appearances_count": 799,
        "notable_seasons": ["1964 FA Cup Winners", "2022-23 Europa Conference League Winners"],
        "famous_matches": ["West Ham 1-0 Fiorentina 2023 Conference League Final"],
        "shirt_sponsor": "Betway",
        "kit_manufacturer": "Umbro",
        "owner": "David Sullivan and David Gold",
        "captain": "Declan Rice",
        "mascot": "Hammerhead"
    },
    "Wolverhampton Wanderers": {
        "nickname": "Wolves",
        "colors": "Gold and Black",
        "stadium": "Molineux Stadium",
        "previous_stadiums": ["Dudley Road"],
        "city": "Wolverhampton",
        "founded": 1877,
        "league": "Premier League",
        "country": "England",
        "legendary_players": ["Billy Wright", "Steve Bull", "John Richards", "Derek Dougan", "Ron Flowers", "Bert Williams"],
        "current_players": ["Matheus Nunes", "Ruben Neves", "Pedro Neto", "Hwang Hee-chan", "Max Kilman"],
        "historical_players": ["Dennis Westcott", "Jimmy Mullen", "Peter Broadbent"],
        "managers": ["Stan Cullis", "Nuno Espirito Santo", "Bruno Lage", "Gary O'Neil", "Mick McCarthy"],
        "trophies": {"league_titles": 3, "fa_cups": 4, "league_cups": 2, "european_trophies": 0},
        "rivals": ["West Bromwich Albion", "Aston Villa", "Birmingham City"],
        "derby_name": "Black Country Derby",
        "record_signing": "Matheus Nunes",
        "record_fee": "45 million",
        "top_scorer": "Steve Bull",
        "top_scorer_goals": 306,
        "most_appearances": "Derek Parkin",
        "most_appearances_count": 609,
        "notable_seasons": ["1953-54 League Champions", "1957-58 League Champions"],
        "famous_matches": ["Wolves 3-2 Honved 1954"],
        "shirt_sponsor": "AstroPay",
        "kit_manufacturer": "Castore",
        "owner": "Fosun International",
        "captain": "Max Kilman",
        "mascot": "Wolfie and Wendy"
    },

    # ==================== BUNDESLIGA ====================
    "Bayern Munich": {
        "nickname": "Der FCB",
        "colors": "Red and White",
        "stadium": "Allianz Arena",
        "previous_stadiums": ["Olympiastadion", "Grunwalder Stadion"],
        "city": "Munich",
        "founded": 1900,
        "league": "Bundesliga",
        "country": "Germany",
        "legendary_players": ["Franz Beckenbauer", "Gerd Muller", "Oliver Kahn", "Philipp Lahm", "Thomas Muller", "Manuel Neuer", "Robert Lewandowski"],
        "current_players": ["Harry Kane", "Jamal Musiala", "Leroy Sane", "Joshua Kimmich", "Alphonso Davies"],
        "historical_players": ["Karl-Heinz Rummenigge", "Lothar Matthaus", "Sepp Maier"],
        "managers": ["Pep Guardiola", "Jupp Heynckes", "Hansi Flick", "Udo Lattek", "Thomas Tuchel", "Vincent Kompany"],
        "trophies": {"league_titles": 33, "dfb_pokal": 20, "european_trophies": 6},
        "rivals": ["Borussia Dortmund", "1860 Munich", "RB Leipzig"],
        "derby_name": "Der Klassiker",
        "record_signing": "Harry Kane",
        "record_fee": "100 million",
        "top_scorer": "Gerd Muller",
        "top_scorer_goals": 566,
        "most_appearances": "Thomas Muller",
        "most_appearances_count": 700,
        "notable_seasons": ["2012-13 Treble", "2019-20 Treble", "1973-74 European Cup"],
        "famous_matches": ["Bayern Munich 1-0 Borussia Dortmund 2013 CL Final"],
        "shirt_sponsor": "Telekom",
        "kit_manufacturer": "Adidas",
        "owner": "Member-owned",
        "captain": "Manuel Neuer",
        "mascot": "Berni"
    },
    "Borussia Dortmund": {
        "nickname": "BVB",
        "colors": "Yellow and Black",
        "stadium": "Signal Iduna Park",
        "previous_stadiums": ["Stadion Rote Erde"],
        "city": "Dortmund",
        "founded": 1909,
        "league": "Bundesliga",
        "country": "Germany",
        "legendary_players": ["Marco Reus", "Jurgen Kohler", "Michael Zorc", "Lars Ricken", "Karl-Heinz Riedle", "Matthias Sammer"],
        "current_players": ["Gregor Kobel", "Nico Schlotterbeck", "Julian Brandt", "Karim Adeyemi", "Sebastien Haller"],
        "historical_players": ["Lothar Emmerich", "Siggi Held", "Adi Preissler"],
        "managers": ["Jurgen Klopp", "Thomas Tuchel", "Ottmar Hitzfeld", "Matthias Sammer", "Edin Terzic"],
        "trophies": {"league_titles": 8, "dfb_pokal": 5, "european_trophies": 1},
        "rivals": ["Bayern Munich", "Schalke 04"],
        "derby_name": "Revierderby",
        "record_signing": "Sebastien Haller",
        "record_fee": "31 million",
        "top_scorer": "Manfred Burgsmüller",
        "top_scorer_goals": 158,
        "most_appearances": "Michael Zorc",
        "most_appearances_count": 572,
        "notable_seasons": ["1996-97 Champions League Winners", "2010-11 Double"],
        "famous_matches": ["Dortmund 3-1 Juventus 1997 CL Final", "Dortmund 4-1 Real Madrid 2013"],
        "shirt_sponsor": "1&1",
        "kit_manufacturer": "Puma",
        "owner": "Member-owned",
        "captain": "Emre Can",
        "mascot": "Emma the Bee"
    },
    "Bayer Leverkusen": {
        "nickname": "Die Werkself",
        "colors": "Red and Black",
        "stadium": "BayArena",
        "previous_stadiums": ["Ulrich-Haberland-Stadion"],
        "city": "Leverkusen",
        "founded": 1904,
        "league": "Bundesliga",
        "country": "Germany",
        "legendary_players": ["Michael Ballack", "Ulf Kirsten", "Rudi Voller", "Bernd Schuster", "Kai Havertz"],
        "current_players": ["Florian Wirtz", "Victor Boniface", "Jeremie Frimpong", "Jonathan Tah", "Granit Xhaka"],
        "historical_players": ["Stefan Kiessling", "Carsten Ramelow", "Ze Roberto"],
        "managers": ["Roger Schmidt", "Peter Bosz", "Xabi Alonso", "Christoph Daum", "Jupp Heynckes"],
        "trophies": {"league_titles": 1, "dfb_pokal": 1, "european_trophies": 1},
        "rivals": ["Borussia Monchengladbach", "FC Koln"],
        "derby_name": "Rhine Derby",
        "record_signing": "Kerem Demirbay",
        "record_fee": "32 million",
        "top_scorer": "Ulf Kirsten",
        "top_scorer_goals": 182,
        "most_appearances": "Stefan Kiessling",
        "most_appearances_count": 386,
        "notable_seasons": ["2001-02 Second in Everything", "2023-24 Invincible Season"],
        "famous_matches": ["Bayer Leverkusen 1-0 Roma 1988 UEFA Cup Final"],
        "shirt_sponsor": "Barmenia",
        "kit_manufacturer": "Castore",
        "owner": "Bayer AG",
        "captain": "Granit Xhaka",
        "mascot": "Brian the Lion"
    },
    "RB Leipzig": {
        "nickname": "Die Roten Bullen",
        "colors": "Red and White",
        "stadium": "Red Bull Arena",
        "previous_stadiums": ["Zentralstadion"],
        "city": "Leipzig",
        "founded": 2009,
        "league": "Bundesliga",
        "country": "Germany",
        "legendary_players": ["Timo Werner", "Emil Forsberg", "Naby Keita", "Yussuf Poulsen"],
        "current_players": ["Christopher Nkunku", "Dominik Szoboszlai", "Dani Olmo", "Xavi Simons"],
        "historical_players": ["Diego Demme", "Stefan Ilsanker"],
        "managers": ["Ralf Rangnick", "Julian Nagelsmann", "Domenico Tedesco", "Marco Rose", "Jesse Marsch"],
        "trophies": {"league_titles": 0, "dfb_pokal": 2, "european_trophies": 0},
        "rivals": ["Bayern Munich", "Borussia Dortmund"],
        "derby_name": "None Traditional",
        "record_signing": "Amadou Haidara",
        "record_fee": "19 million",
        "top_scorer": "Timo Werner",
        "top_scorer_goals": 95,
        "most_appearances": "Yussuf Poulsen",
        "most_appearances_count": 311,
        "notable_seasons": ["2019-20 Champions League Semi-Finals"],
        "famous_matches": ["RB Leipzig 3-0 Tottenham 2020 CL Round of 16"],
        "shirt_sponsor": "Red Bull",
        "kit_manufacturer": "Nike",
        "owner": "Red Bull GmbH",
        "captain": "Willi Orban",
        "mascot": "Bulli"
    },
    "VfB Stuttgart": {
        "nickname": "Die Schwaben",
        "colors": "White and Red",
        "stadium": "Mercedes-Benz Arena",
        "previous_stadiums": ["Neckarstadion"],
        "city": "Stuttgart",
        "founded": 1893,
        "league": "Bundesliga",
        "country": "Germany",
        "legendary_players": ["Jurgen Klinsmann", "Karl Allgower", "Karlheinz Forster", "Fredi Bobic", "Kevin Kuranyi"],
        "current_players": ["Serhou Guirassy", "Chris Fuhrich", "Waldemar Anton", "Enzo Millot"],
        "historical_players": ["Hansi Muller", "Guido Buchwald", "Robert Schlienz"],
        "managers": ["Giovanni Trapattoni", "Armin Veh", "Bruno Labbadia", "Sebastian Hoeness"],
        "trophies": {"league_titles": 5, "dfb_pokal": 3, "european_trophies": 0},
        "rivals": ["Karlsruher SC", "Bayern Munich"],
        "derby_name": "Baden-Wurttemberg Derby",
        "record_signing": "Orel Mangala",
        "record_fee": "13 million",
        "top_scorer": "Robert Schlienz",
        "top_scorer_goals": 107,
        "most_appearances": "Karlheinz Forster",
        "most_appearances_count": 404,
        "notable_seasons": ["1991-92 Bundesliga Champions", "2006-07 Bundesliga Champions"],
        "famous_matches": ["Stuttgart 2-1 Barcelona 2010 Champions League"],
        "shirt_sponsor": "Mercedes-Benz",
        "kit_manufacturer": "Jako",
        "owner": "Member-owned",
        "captain": "Wataru Endo",
        "mascot": "Fritzle"
    },
    "Eintracht Frankfurt": {
        "nickname": "Die Adler",
        "colors": "Red, Black and White",
        "stadium": "Deutsche Bank Park",
        "previous_stadiums": ["Waldstadion"],
        "city": "Frankfurt",
        "founded": 1899,
        "league": "Bundesliga",
        "country": "Germany",
        "legendary_players": ["Anthony Yeboah", "Jay-Jay Okocha", "Cha Bum-kun", "Jurgen Grabowski", "Bernd Holzenbein"],
        "current_players": ["Randal Kolo Muani", "Jesper Lindstrom", "Mario Gotze", "Kevin Trapp"],
        "historical_players": ["Alfred Pfaff", "Freddy Himmelmann", "Bruno Pezzey"],
        "managers": ["Niko Kovac", "Oliver Glasner", "Adi Hutter", "Thomas Schaaf"],
        "trophies": {"league_titles": 1, "dfb_pokal": 5, "european_trophies": 2},
        "rivals": ["Kickers Offenbach", "1. FSV Mainz 05"],
        "derby_name": "Hessen Derby",
        "record_signing": "Randal Kolo Muani",
        "record_fee": "23 million",
        "top_scorer": "Bernd Nickel",
        "top_scorer_goals": 157,
        "most_appearances": "Charly Koerbel",
        "most_appearances_count": 602,
        "notable_seasons": ["2021-22 Europa League Winners"],
        "famous_matches": ["Eintracht Frankfurt 1-1 Rangers (5-4 pens) 2022 Europa League Final"],
        "shirt_sponsor": "Indeed",
        "kit_manufacturer": "Nike",
        "owner": "Member-owned",
        "captain": "Sebastian Rode",
        "mascot": "Attila the Eagle"
    },
    "SC Freiburg": {
        "nickname": "Breisgau-Brasilianer",
        "colors": "Red and White",
        "stadium": "Europa-Park Stadion",
        "previous_stadiums": ["Dreisamstadion"],
        "city": "Freiburg",
        "founded": 1904,
        "league": "Bundesliga",
        "country": "Germany",
        "legendary_players": ["Volker Finke", "Nils Petersen", "Jonathan Schmid", "Papiss Cisse"],
        "current_players": ["Vincenzo Grifo", "Michael Gregoritsch", "Christian Gunter", "Manuel Gulde"],
        "historical_players": ["Rodolfo Esteban Cardoso", "Uwe Wassmer", "Jorg Heinrich"],
        "managers": ["Volker Finke", "Robin Dutt", "Christian Streich", "Julian Schuster"],
        "trophies": {"league_titles": 0, "dfb_pokal": 0, "european_trophies": 0},
        "rivals": ["VfB Stuttgart", "Karlsruher SC"],
        "derby_name": "Baden Derby",
        "record_signing": "Merlin Rohl",
        "record_fee": "7 million",
        "top_scorer": "Nils Petersen",
        "top_scorer_goals": 115,
        "most_appearances": "Christian Gunter",
        "most_appearances_count": 402,
        "notable_seasons": ["2022-23 DFB-Pokal Final"],
        "famous_matches": ["Freiburg 3-3 RB Leipzig 2023 DFB-Pokal Final"],
        "shirt_sponsor": "Schwarzwald Tourismus",
        "kit_manufacturer": "Hummel",
        "owner": "Member-owned",
        "captain": "Christian Gunter",
        "mascot": "Fuchsle"
    },
    "VfL Wolfsburg": {
        "nickname": "Die Wolfe",
        "colors": "Green and White",
        "stadium": "Volkswagen Arena",
        "previous_stadiums": ["VfL-Stadion"],
        "city": "Wolfsburg",
        "founded": 1945,
        "league": "Bundesliga",
        "country": "Germany",
        "legendary_players": ["Grafite", "Edin Dzeko", "Kevin De Bruyne", "Diego Benaglio", "Diego"],
        "current_players": ["Patrick Wimmer", "Ridle Baku", "Maximilian Arnold", "Micky van de Ven"],
        "historical_players": ["Roy Praeger", "Siegfried Reich", "Krzysztof Nowak"],
        "managers": ["Felix Magath", "Niko Kovac", "Mark van Bommel", "Bruno Labbadia"],
        "trophies": {"league_titles": 1, "dfb_pokal": 1, "european_trophies": 0},
        "rivals": ["Hannover 96", "Werder Bremen"],
        "derby_name": "Lower Saxony Derby",
        "record_signing": "Julian Draxler",
        "record_fee": "35 million",
        "top_scorer": "Edin Dzeko",
        "top_scorer_goals": 85,
        "most_appearances": "Maximilian Arnold",
        "most_appearances_count": 394,
        "notable_seasons": ["2008-09 Bundesliga Champions"],
        "famous_matches": ["Wolfsburg 5-1 Bayern Munich 2009"],
        "shirt_sponsor": "Volkswagen",
        "kit_manufacturer": "Nike",
        "owner": "Volkswagen AG",
        "captain": "Maximilian Arnold",
        "mascot": "Wolfi"
    },
    "TSG Hoffenheim": {
        "nickname": "Die Kraichgauer",
        "colors": "Blue and White",
        "stadium": "PreZero Arena",
        "previous_stadiums": ["Dietmar-Hopp-Stadion"],
        "city": "Sinsheim",
        "founded": 1899,
        "league": "Bundesliga",
        "country": "Germany",
        "legendary_players": ["Vedad Ibisevic", "Demba Ba", "Roberto Firmino", "Sejad Salihovic"],
        "current_players": ["Andrej Kramaric", "Ozan Kabak", "Florian Grillitsch", "Angelino"],
        "historical_players": ["Chinedu Obasi", "Luiz Gustavo", "Ryan Babel"],
        "managers": ["Julian Nagelsmann", "Alfred Schreuder", "Sebastian Hoeness", "Pellegrino Matarazzo"],
        "trophies": {"league_titles": 0, "dfb_pokal": 0, "european_trophies": 0},
        "rivals": ["Karlsruher SC", "VfB Stuttgart"],
        "derby_name": "None Traditional",
        "record_signing": "Lucas Ribeiro",
        "record_fee": "8 million",
        "top_scorer": "Andrej Kramaric",
        "top_scorer_goals": 105,
        "most_appearances": "Oliver Baumann",
        "most_appearances_count": 313,
        "notable_seasons": ["2017-18 Champions League Qualification"],
        "famous_matches": ["Hoffenheim 4-1 Bayern Munich 2020"],
        "shirt_sponsor": "SAP",
        "kit_manufacturer": "Joma",
        "owner": "Dietmar Hopp",
        "captain": "Oliver Baumann",
        "mascot": "Hoffi"
    },
    "1. FC Union Berlin": {
        "nickname": "Die Eisernen",
        "colors": "Red and White",
        "stadium": "Stadion An der Alten Forsterei",
        "previous_stadiums": [],
        "city": "Berlin",
        "founded": 1966,
        "league": "Bundesliga",
        "country": "Germany",
        "legendary_players": ["Sebastian Polter", "Marvin Friedrich", "Max Kruse", "Robert Andersson"],
        "current_players": ["Sheraldo Becker", "Robin Knoche", "Rani Khedira", "Kevin Volland"],
        "historical_players": ["Hans-Jurgen Doerner", "Rainer Troppa", "Rainer Ernst"],
        "managers": ["Urs Fischer", "Jens Keller", "Nenad Bjelica", "Bo Svensson"],
        "trophies": {"league_titles": 0, "dfb_pokal": 0, "european_trophies": 0},
        "rivals": ["Hertha BSC"],
        "derby_name": "Berlin Derby",
        "record_signing": "Aissa Laidouni",
        "record_fee": "7 million",
        "top_scorer": "Sebastian Polter",
        "top_scorer_goals": 33,
        "most_appearances": "Christopher Trimmel",
        "most_appearances_count": 266,
        "notable_seasons": ["2022-23 Champions League Qualification"],
        "famous_matches": ["Union Berlin 2-0 Hertha BSC 2019"],
        "shirt_sponsor": "Atera",
        "kit_manufacturer": "Adidas",
        "owner": "Member-owned",
        "captain": "Christopher Trimmel",
        "mascot": "Ritter Keule"
    },
    "Borussia Monchengladbach": {
        "nickname": "Die Fohlen",
        "colors": "White, Green and Black",
        "stadium": "Borussia-Park",
        "previous_stadiums": ["Bokelbergstadion"],
        "city": "Monchengladbach",
        "founded": 1900,
        "league": "Bundesliga",
        "country": "Germany",
        "legendary_players": ["Lothar Matthaus", "Jupp Heynckes", "Gunter Netzer", "Berti Vogts", "Stefan Effenberg"],
        "current_players": ["Jonas Hofmann", "Marcus Thuram", "Florian Neuhaus", "Yann Sommer"],
        "historical_players": ["Uwe Rahn", "Herbert Laumen", "Wolfgang Kleff"],
        "managers": ["Hennes Weisweiler", "Lucien Favre", "Marco Rose", "Adi Hutter", "Gerardo Seoane"],
        "trophies": {"league_titles": 5, "dfb_pokal": 3, "european_trophies": 2},
        "rivals": ["FC Koln", "Bayer Leverkusen"],
        "derby_name": "Rhine Derby",
        "record_signing": "Marcus Thuram",
        "record_fee": "12 million",
        "top_scorer": "Jupp Heynckes",
        "top_scorer_goals": 195,
        "most_appearances": "Berti Vogts",
        "most_appearances_count": 419,
        "notable_seasons": ["1970-75 Five Bundesliga Titles", "1974-75 UEFA Cup Winners"],
        "famous_matches": ["Borussia Monchengladbach 7-1 Inter Milan 1971"],
        "shirt_sponsor": "Postbank",
        "kit_manufacturer": "Puma",
        "owner": "Member-owned",
        "captain": "Lars Stindl",
        "mascot": "Junter"
    },
    "1. FSV Mainz 05": {
        "nickname": "Die Nullfunfer",
        "colors": "Red and White",
        "stadium": "Mewa Arena",
        "previous_stadiums": ["Bruchwegstadion"],
        "city": "Mainz",
        "founded": 1905,
        "league": "Bundesliga",
        "country": "Germany",
        "legendary_players": ["Jurgen Klopp", "Andre Schurrle", "Mohamed Zidan", "Sami Allagui"],
        "current_players": ["Karim Onisiwo", "Lee Jae-sung", "Anthony Caci", "Robin Zentner"],
        "historical_players": ["Nikolce Noveski", "Andreas Ivanschitz", "Eugen Polanski"],
        "managers": ["Jurgen Klopp", "Thomas Tuchel", "Bo Svensson", "Jan-Moritz Lichte"],
        "trophies": {"league_titles": 0, "dfb_pokal": 0, "european_trophies": 0},
        "rivals": ["Eintracht Frankfurt", "1. FC Kaiserslautern"],
        "derby_name": "Rhine-Main Derby",
        "record_signing": "Moussa Niakhate",
        "record_fee": "10 million",
        "top_scorer": "Mohamed Zidan",
        "top_scorer_goals": 37,
        "most_appearances": "Stefan Bell",
        "most_appearances_count": 232,
        "notable_seasons": ["2010-11 Europa League Quarter-Finals"],
        "famous_matches": ["Mainz 05 2-0 Borussia Dortmund 2021"],
        "shirt_sponsor": "Koemmerling",
        "kit_manufacturer": "Nike",
        "owner": "Member-owned",
        "captain": "Silvan Widmer",
        "mascot": "Mainzelmännchen"
    },
    "SV Werder Bremen": {
        "nickname": "Die Werderaner",
        "colors": "Green and White",
        "stadium": "Weserstadion",
        "previous_stadiums": [],
        "city": "Bremen",
        "founded": 1899,
        "league": "Bundesliga",
        "country": "Germany",
        "legendary_players": ["Rudi Voller", "Karl-Heinz Riedle", "Miroslav Klose", "Diego", "Claudio Pizarro", "Per Mertesacker"],
        "current_players": ["Niclas Fullkrug", "Marvin Ducksch", "Mitchell Weiser", "Jens Stage"],
        "historical_players": ["Otto Rehhagel", "Wynton Rufer", "Marco Bode"],
        "managers": ["Otto Rehhagel", "Thomas Schaaf", "Ole Werner", "Florian Kohfeldt"],
        "trophies": {"league_titles": 4, "dfb_pokal": 6, "european_trophies": 1},
        "rivals": ["Hamburger SV", "Hannover 96"],
        "derby_name": "Nordderby",
        "record_signing": "Marko Arnautovic",
        "record_fee": "8 million",
        "top_scorer": "Claudio Pizarro",
        "top_scorer_goals": 153,
        "most_appearances": "Dieter Burdenski",
        "most_appearances_count": 444,
        "notable_seasons": ["2003-04 Double", "2008-09 UEFA Cup Final"],
        "famous_matches": ["Werder Bremen 4-0 Bayern Munich 2004"],
        "shirt_sponsor": "Wiesenhof",
        "kit_manufacturer": "Umbro",
        "owner": "Member-owned",
        "captain": "Marco Friedl",
        "mascot": "Werdi"
    },
    "FC Augsburg": {
        "nickname": "Die Fuggerstadter",
        "colors": "Red, Green and White",
        "stadium": "WWK Arena",
        "previous_stadiums": ["Rosenaustadion"],
        "city": "Augsburg",
        "founded": 1907,
        "league": "Bundesliga",
        "country": "Germany",
        "legendary_players": ["Halil Altintop", "Daniel Baier", "Sascha Molders", "Raul Bobadilla"],
        "current_players": ["Ermedin Demirovic", "Jeffrey Gouweleeuw", "Niklas Dorsch", "Elvis Rexhbecaj"],
        "historical_players": ["Helmut Haller", "Bernd Schuster", "Tobias Werner"],
        "managers": ["Manuel Baum", "Markus Weinzierl", "Enrico Maassen", "Jess Thorup"],
        "trophies": {"league_titles": 0, "dfb_pokal": 0, "european_trophies": 0},
        "rivals": ["TSV 1860 Munich", "1. FC Nurnberg"],
        "derby_name": "Bavarian Derby",
        "record_signing": "Ricardo Pepi",
        "record_fee": "16 million",
        "top_scorer": "Alfred Nijhuis",
        "top_scorer_goals": 52,
        "most_appearances": "Daniel Baier",
        "most_appearances_count": 337,
        "notable_seasons": ["2015-16 Europa League Group Stage"],
        "famous_matches": ["FC Augsburg 1-0 Bayern Munich 2015"],
        "shirt_sponsor": "WWK Versicherung",
        "kit_manufacturer": "Nike",
        "owner": "Klaus Hofmann",
        "captain": "Jeffrey Gouweleeuw",
        "mascot": "Fuggeri"
    },
    "VfL Bochum": {
        "nickname": "Die Unabsteigbaren",
        "colors": "Blue and White",
        "stadium": "Vonovia Ruhrstadion",
        "previous_stadiums": [],
        "city": "Bochum",
        "founded": 1848,
        "league": "Bundesliga",
        "country": "Germany",
        "legendary_players": ["Simon Zoller", "Michael Lameck", "Hermann Gerland", "Hans-Joachim Abel"],
        "current_players": ["Philipp Hofmann", "Anthony Losilla", "Kevin Stoger", "Cristian Gamboa"],
        "historical_players": ["Franz-Josef Tenhagen", "Jupp Tenhagen", "Lothar Woelk"],
        "managers": ["Peter Neururer", "Thomas Reis", "Heiko Butscher", "Letsch"],
        "trophies": {"league_titles": 0, "dfb_pokal": 0, "european_trophies": 0},
        "rivals": ["Borussia Dortmund", "Schalke 04"],
        "derby_name": "Ruhr Derby",
        "record_signing": "Philipp Hofmann",
        "record_fee": "2 million",
        "top_scorer": "Hans-Joachim Abel",
        "top_scorer_goals": 133,
        "most_appearances": "Michael Lameck",
        "most_appearances_count": 466,
        "notable_seasons": ["2020-21 Promotion to Bundesliga"],
        "famous_matches": ["Bochum 4-3 Bayern Munich 2022"],
        "shirt_sponsor": "Vonovia",
        "kit_manufacturer": "Nike",
        "owner": "Member-owned",
        "captain": "Anthony Losilla",
        "mascot": "Bobbi"
    },
    "1. FC Heidenheim": {
        "nickname": "Die Brenz",
        "colors": "Red and Blue",
        "stadium": "Voith-Arena",
        "previous_stadiums": ["Albstadion"],
        "city": "Heidenheim",
        "founded": 1946,
        "league": "Bundesliga",
        "country": "Germany",
        "legendary_players": ["Marc Schnatterer", "Norman Theuerkauf", "Tim Kleindienst"],
        "current_players": ["Jan-Niklas Beste", "Tim Kleindienst", "Kevin Muller", "Patrick Mainka"],
        "historical_players": ["Robert Strauss", "Arne Feick", "Maximilian Thiel"],
        "managers": ["Frank Schmidt"],
        "trophies": {"league_titles": 0, "dfb_pokal": 0, "european_trophies": 0},
        "rivals": ["VfB Stuttgart"],
        "derby_name": "Baden-Wurttemberg Derby",
        "record_signing": "Tim Kleindienst",
        "record_fee": "2 million",
        "top_scorer": "Marc Schnatterer",
        "top_scorer_goals": 105,
        "most_appearances": "Marc Schnatterer",
        "most_appearances_count": 403,
        "notable_seasons": ["2022-23 Bundesliga Promotion"],
        "famous_matches": ["Heidenheim 2-2 Werder Bremen 2023 Promotion Playoff"],
        "shirt_sponsor": "Voith",
        "kit_manufacturer": "Nike",
        "owner": "Member-owned",
        "captain": "Patrick Mainka",
        "mascot": "Paule"
    },
    "FC St. Pauli": {
        "nickname": "Die Kiezkicker",
        "colors": "Brown and White",
        "stadium": "Millerntor-Stadion",
        "previous_stadiums": [],
        "city": "Hamburg",
        "founded": 1910,
        "league": "Bundesliga",
        "country": "Germany",
        "legendary_players": ["Fabian Boll", "Timo Schultz", "Holger Stanislawski", "Gerald Asamoah"],
        "current_players": ["Jackson Irvine", "Oladapo Afolayan", "Manolis Saliakas", "Johannes Eggestein"],
        "historical_players": ["Klaus Thomforde", "Andre Trulsen", "Deniz Naki"],
        "managers": ["Holger Stanislawski", "Jos Luhukay", "Timo Schultz", "Fabian Hurzeler"],
        "trophies": {"league_titles": 0, "dfb_pokal": 0, "european_trophies": 0},
        "rivals": ["Hamburger SV"],
        "derby_name": "Hamburg Derby",
        "record_signing": "Marcel Hartel",
        "record_fee": "2 million",
        "top_scorer": "Walter Risse",
        "top_scorer_goals": 86,
        "most_appearances": "Klaus Thomforde",
        "most_appearances_count": 399,
        "notable_seasons": ["2023-24 2. Bundesliga Champions"],
        "famous_matches": ["St. Pauli 2-1 Bayern Munich 2002 DFB-Pokal"],
        "shirt_sponsor": "Congstar",
        "kit_manufacturer": "Hummel",
        "owner": "Member-owned",
        "captain": "Jackson Irvine",
        "mascot": "None - Skull and Crossbones Flag"
    },
    "Holstein Kiel": {
        "nickname": "Die Storche",
        "colors": "Blue and White",
        "stadium": "Holstein-Stadion",
        "previous_stadiums": [],
        "city": "Kiel",
        "founded": 1900,
        "league": "Bundesliga",
        "country": "Germany",
        "legendary_players": ["Fabian Reese", "Lewis Holtby", "Jannik Dehm", "Alexander Muhling"],
        "current_players": ["Shuto Machino", "Phil Harres", "Timo Becker", "Alexander Muhling"],
        "historical_players": ["Niklas Hauptmann", "Jae-sung Lee", "David Kinsombi"],
        "managers": ["Marcel Rapp", "Ole Werner", "Andre Schubert"],
        "trophies": {"league_titles": 0, "dfb_pokal": 0, "european_trophies": 0},
        "rivals": ["Hamburger SV", "St. Pauli"],
        "derby_name": "Northern Derby",
        "record_signing": "Shuto Machino",
        "record_fee": "2 million",
        "top_scorer": "Erwin Seeler",
        "top_scorer_goals": 114,
        "most_appearances": "Karl-Heinz Borkowski",
        "most_appearances_count": 338,
        "notable_seasons": ["2023-24 Bundesliga Promotion"],
        "famous_matches": ["Holstein Kiel 8-2 Bayern Munich 2021 DFB-Pokal"],
        "shirt_sponsor": "CG Gruppe",
        "kit_manufacturer": "Macron",
        "owner": "Member-owned",
        "captain": "Lewis Holtby",
        "mascot": "Storcky"
    },
}
