"""Add favorite_club and club_knowledge_score to users

Revision ID: 10c448f09924
Revises: baf3d2673bb4
Create Date: 2026-02-09 22:00:49.966834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c448f09924'
down_revision: Union[str, Sequence[str], None] = 'baf3d2673bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_club', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('club_knowledge_score', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_favorite_club'), 'users', ['favorite_club'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_favorite_club'), table_name='users')
    op.drop_column('users', 'club_knowledge_score')
    op.drop_column('users', 'favorite_club')
    # ### end Alembic commands ###
