"""add_matchmaking_queue_table

Revision ID: 3c6d71858694
Revises: d18346b0352c
Create Date: 2026-02-10 11:16:24.714507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6d71858694'
down_revision: Union[str, Sequence[str], None] = 'd18346b0352c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchmaking_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skill_rank', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_matchmaking_skill', 'matchmaking_queue', ['skill_rank'], unique=False)
    op.create_index('idx_matchmaking_status_skill', 'matchmaking_queue', ['status', 'skill_rank'], unique=False)
    op.create_index(op.f('ix_matchmaking_queue_user_id'), 'matchmaking_queue', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matchmaking_queue_user_id'), table_name='matchmaking_queue')
    op.drop_index('idx_matchmaking_status_skill', table_name='matchmaking_queue')
    op.drop_index('idx_matchmaking_skill', table_name='matchmaking_queue')
    op.drop_table('matchmaking_queue')
    # ### end Alembic commands ###
