"""Initial schema with users, sessions, questions, games, and rounds

Revision ID: baf3d2673bb4
Revises: 
Create Date: 2026-02-09 21:25:22.255532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf3d2673bb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.String(length=500), nullable=False),
    sa.Column('option_b', sa.String(length=500), nullable=False),
    sa.Column('option_c', sa.String(length=500), nullable=False),
    sa.Column('option_d', sa.String(length=500), nullable=False),
    sa.Column('correct_option', sa.String(length=1), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_difficulty', 'questions', ['category', 'difficulty'], unique=False)
    op.create_index(op.f('ix_questions_category'), 'questions', ['category'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('picture', sa.String(length=500), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('skill_rank', sa.Integer(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player1_id', sa.String(length=36), nullable=False),
    sa.Column('player2_id', sa.String(length=36), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('turn_player_id', sa.String(length=36), nullable=True),
    sa.Column('winner_id', sa.String(length=36), nullable=True),
    sa.Column('invite_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player2_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_player_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_invite_code'), 'games', ['invite_code'], unique=True)
    op.create_index(op.f('ix_games_player1_id'), 'games', ['player1_id'], unique=False)
    op.create_index(op.f('ix_games_player2_id'), 'games', ['player2_id'], unique=False)
    op.create_index(op.f('ix_games_status'), 'games', ['status'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('game_rounds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('category_selected', sa.String(length=100), nullable=True),
    sa.Column('player1_answers', sa.JSON(), nullable=True),
    sa.Column('player2_answers', sa.JSON(), nullable=True),
    sa.Column('player1_score', sa.Integer(), nullable=True),
    sa.Column('player2_score', sa.Integer(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_game_round', 'game_rounds', ['game_id', 'round_number'], unique=False)
    op.create_index(op.f('ix_game_rounds_game_id'), 'game_rounds', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_rounds_game_id'), table_name='game_rounds')
    op.drop_index('idx_game_round', table_name='game_rounds')
    op.drop_table('game_rounds')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_games_status'), table_name='games')
    op.drop_index(op.f('ix_games_player2_id'), table_name='games')
    op.drop_index(op.f('ix_games_player1_id'), table_name='games')
    op.drop_index(op.f('ix_games_invite_code'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_questions_category'), table_name='questions')
    op.drop_index('idx_category_difficulty', table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
