"""Add country age phone and leagues support

Revision ID: d18346b0352c
Revises: 10c448f09924
Create Date: 2026-02-09 22:32:07.193355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18346b0352c'
down_revision: Union[str, Sequence[str], None] = '10c448f09924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('league_type', sa.String(length=20), nullable=False),
    sa.Column('invite_code', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_invite_code'), 'leagues', ['invite_code'], unique=True)
    op.create_index(op.f('ix_leagues_league_type'), 'leagues', ['league_type'], unique=False)
    op.create_table('league_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('league_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_league_user', 'league_memberships', ['league_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_league_memberships_league_id'), 'league_memberships', ['league_id'], unique=False)
    op.create_index(op.f('ix_league_memberships_user_id'), 'league_memberships', ['user_id'], unique=False)
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_country'), 'users', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_country'), table_name='users')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'age')
    op.drop_column('users', 'country')
    op.drop_index(op.f('ix_league_memberships_user_id'), table_name='league_memberships')
    op.drop_index(op.f('ix_league_memberships_league_id'), table_name='league_memberships')
    op.drop_index('idx_league_user', table_name='league_memberships')
    op.drop_table('league_memberships')
    op.drop_index(op.f('ix_leagues_league_type'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_invite_code'), table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###
